### ISSUE TITLE
해당 저장소 setup 시 문제점과 해결방안, 그리고 몇 가지 여쭙고 싶습니다.

### ISSUE THREAD

**Issue by Foreist** [haven-jeon/Train_KoSpacing#1]
일단 gpu 연산을 통한 학습을 위해서는 기존 requirements 설치 이후requirements에서 mxnet을 mxnet-cu100==1.6.0b20191101으로 설치해야 했습니다.
requirements에 기입된 mxnet으로는 params 에러가 나더라고요.
학습에 필요한 파일들은 data 폴더를 만들고 그 안에 txt.bz2로 압축을 해주었습니다.
그리고 train.py
366 print(n_gram[0])
367 print(n_gram_y[0])
379 print(ngram_coding_seq[0])
에 해당하는 것들은 [0]을 주석처리 해야 하더라고요.
해당 부분을 주석처리하지 않거나 [0]을 빼주지 않으면 범위를 벗어났다는 에러가 발생해서요!
(해당 부분을 주석처리하고 학습이 0%에서 진행이 되지 않는 경우도 발생했으나 원인규명이 불가능했습니다.)

일단 위의 방식이 제가 영어+한국 문장을 학습을 시키기까지 문제점과 해결방안들인데요.
혹시 위 방법으로 처리를 하였을 때 우려사항이라거나 문제점이 있다면 듣고 싶습니다.

그리고 해당 코드에서는 train, val, test가 아니라 train, test, val로 해서  나누셨더라고요!
학습할 dataset에서 --train-sample-ratio에서 train data의 일정 data를 test셋으로 나누어서 가령 --train-sample-ratio가 0.5라면 
0.5가 train, 0.5가 test로 들어가서 제가 validation으로 넣은 데이터가 모델 pre-train 과정에서 train data를 train data에서 분리한 test data로 검증 후에 val로 결과가 되던데 이 부분이 제가 제대로 이해하고 모델을 돌렸는지 궁금합니다.

그리고 제가 5만 줄 정도 학습을 시켰는데 python train.py --model-params model/kospacing.params 을 통해서는 인퍼런스 타임이 조금 오래 걸려서 인퍼런스하는 코드만 따로 떼서 time()을 재보니 0.2초 정도가 소요되던데 원 모델인 kospacing은 0.03 정도가 평균적으로 소요되는 시간이더라고요.
인퍼런스 타임을 기존 kospacing처럼 줄이고 싶습니다.
혹시 해당 모델에서는 학습만 시키고 학습시킨 모델을 pykospacing에 따로 이식을 해서 사용을 해야 하는지, 그렇게 해야 한다면 params만 
https://github.com/haven-jeon/PyKoSpacing/tree/master/pykospacing/resources/models
에 해당하는 경로에 넣어서 처리를 하면 될까요?

제 문의사항은 Update README.md commit까지 업데이트된 파일을 기준으로 작성되었습니다.

질문이 조금 많네요 ㅠㅠ 해당 모델에 관심이 많습니다.
저도 이 모델을 정상적으로 다른 분들이 쉽게 학습하고 기존 kospacing 인퍼런스 타임을 가져갈 수 있도록 조금이라도 기여가 되었으면 좋겠습니다.
읽어주셔서 감사합니다.

**Comment by haven-jeon** [comment]
1. mxnet은 cuda버전에 따라서 사용자가 설치를 별도 해줘야 되는 부분이여서 일단 범용적인 CPU 버전으로 설치 진행했습니다(제가 사용자의 CUDA버전을 알 수가 없기에..). 이 부분에 대한 README는 포함될 필요가 있겠네요.
2. 학습에 필요한 파일을 bz2으로 해줘야 되는거 맞습니다. 이 부분 명령형 인자로 뽑게 해놓았는데, 업데이트 하도록 하겠습니다.
3.  print()... 이부분들은 제 쪽에서는 에러가 나지 않습니다. 왜그런지 모르겠네요.
4. 이 부분은 올바르게 fix 해야 될거 같습니다.(train, valid, test)
5.  `kospacing처럼 줄이고 싶습니다.` 모델 인퍼런스 속도를 향상 시킬 수 있는 방법은 다양해서 뭐가 좋을지는 모르겠습니다. 일단 `mxnet-mkl` 계열로 테스트 해보시면 속도향상이 될 겁니다. 


관심 주셔서 감사합니다.

**Comment by haven-jeon** [comment]
위 부분들 이슈도 있었지만, 모델에 버그가 있어서 수정 했습니다. 필터 몇개가 잘못 적용되어 있었네요..

eb598d89fc16616bfb8263685af0ce4f38bf2d6d

새로 받아서 학습하세요.

**Comment by haven-jeon** [comment]
cpu 상에서 인터런스 속도를 봤습니다.  참고로 제 테스트 환경은 Ryzen3 듀얼코어입니다.  
먼저 mxnet cpu only 버전에서는 아래와 같습니다.

```
$ python train.py --model-params model/kospacing.params --model_type kospacing
sent > 는'1987'의네이버영화정보네티즌10점평에서언급된
는'1987'의네이버영화정보네티즌10점평에서언급된
spaced sent[0.14sec/sent]  > 는 '1987'의 네이버 영화 정보 네티즌 10점평에서 언급된 
sent > 7일부터올해1월10일까지통계프로그램R
7일부터올해1월10일까지통계프로그램R
spaced sent[0.14sec/sent]  > 7일부터 올해 1월 10일까지 통계 프로그램 R 
sent > 지로텍스트마이닝하여분석했다.
지로텍스트마이닝하여분석했다.
spaced sent[0.14sec/sent]  > 지로 텍스트 마이닝 하여 분석했다. 
```
약 0.14초 나오네요.

아래는 mxnet-mkl 기반 테스트입니다. 
```
$ python train.py --model-params model/kospacing.params --model_type kospacing
sent > 는'1987'의네이버영화정보네티즌10점평에서언급된
는'1987'의네이버영화정보네티즌10점평에서언급된
spaced sent[0.06sec/sent]  > 는 '1987'의 네이버 영화 정보 네티즌 10점평에서 언급된 
sent > 7일부터올해1월10일까지통계프로그램R
7일부터올해1월10일까지통계프로그램R
spaced sent[0.06sec/sent]  > 7일부터 올해 1월 10일까지 통계 프로그램 R 
sent > 지로텍스트마이닝하여분석했다.
지로텍스트마이닝하여분석했다.
spaced sent[0.07sec/sent]  > 지로 텍스트 마이닝 하여 분석했다. 
```

약 반으로 인퍼런스 속도가 줄어드네요.  ^^

만일 mxnet-mkl로 전환하고 싶으시면 pip uninstall로 기존 버전을 완전히 삭제하고 설치하시는 걸 추천드립니다.

**Comment by Foreist** [comment]
늦게 답장드려 죄송합니다. 자세하게 설명해 주셔서 감사합니다! 해당 이슈는 종료하도록 하겠습니다~
